### ISSUE TITLE
Feature suggestion: blacklist for items

### ISSUE THREAD

**Issue by TheDinoKingK** [skulldogged/dropconfirm-OLD#3]
basically, a blacklist config to exclude items from the drop confirmation functionality,
so If you find yourself removing a particular item constantly or know that you don't need it that much,
you can add it to the list so it won't bother asking if you are sure you don't want to drop the item, the list would be blank by default

**Comment by skulldogged** [comment]
Added in 1.4.0 - let me know if there are any issues.

(FYI, the 1.19.4 backport doesn't contain this feature due to the ItemController not being in the latest version of YetAnotherConfigLib for 1.19.4)
