### ISSUE TITLE
Backport request: 1.19.4

### ISSUE THREAD

**Issue by Mr-Jokes-3** [skulldogged/dropconfirm-OLD#4]
Will you be considering a 1.19.4 backport?

**Comment by skulldogged** [comment]
[Done.](https://github.com/pupbrained/drop-confirm/releases/tag/1.3.1-1.19.4)

Let me know if there's any issues, and make sure you have the latest versions of YetAnotherConfigLibrary and ModMenu for 1.19.4 installed.
